events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html;
        autoindex on;
        autoindex_exact_size on;
        autoindex_localtime off;
        autoindex_format html;

        add_header Server "Apache/2.2.15 (CentOS)";

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
